name: deploy-storybook

run-name: ${{ github.actor }} is started the action

on:
  push:
    branches:
      - "main"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - run: npm ci
    # - name: Run test
    #   run: npm run test
    # - name: Deploy storybook
    #   uses: bitovi/github-actions-storybook-to-github-pages@v1.0.2
    #   with:
    #     path: ./packages/ds/storybook-static
    - name: Run build
      run: npm run build
    - name: Publish ui-blocks package to npm
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
      run: npm publish