name: deploy-storybook

run-name: ${{ github.actor }} is started the action

on:
  push:
    branches:
      - "main"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  find-changes:
    runs-on: ubuntu-latest
    outputs:
      changed_packages: ${{steps.versions_checker.outputs.changed_packages}}
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - run: git checkout ${{ github.ref_name }}
    - id: versions_checker
      # run: echo "changed_packages=@ui-blocks/common" >> "$GITHUB_OUTPUT"
      run: node utils/showChangedPackageVersions.js >> "$GITHUB_OUTPUT"
  deploy:
    runs-on: ubuntu-latest
    needs: find-changes
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        registry-url: 'https://registry.npmjs.org'

      if: contains(needs.find-changes.outputs.changed_packages, '@ui-blocks/common')
    - run: echo "@ui-blocks/common version changed"

      if: contains(needs.find-changes.outputs.changed_packages, '@ui-blocks/ds')
    - run: echo "@ui-blocks/ds version changed"
    # - name: Run test
    #   run: npm run test
    # - name: Deploy storybook
    #   uses: bitovi/github-actions-storybook-to-github-pages@v1.0.2
    #   with:
    #     path: ./packages/ds/storybook-static
    # - name: Install packages in @ui-blocks/common
    #   run: npm i -w @ui-blocks/common
    # - name: Run build for common package
    #   run: npm run build:common
    # - name: Publish common package to npm registry
    #   run: npm publish --access public -w @ui-blocks/common
    #   env:
    #     NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
    # - name: Install packages in @ui-blocks/ui-blocks
    #   run: npm i -w @ui-blocks/ds
    # - name: Run build for design-system
    #   run: npm run build:ds
    # - name: Publish ui-blocks package to npm registry
    #   run: npm publish --access public -w @ui-blocks/ds
    #   env:
    #     NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}


