name: ds-test

run-name: ${{ github.actor }} is started the action

on: [push]

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm run test